{Hi|Hello there} my suspicious friend!

Curious who has been leaking your company secrets to the {press|media}?

Canary is a super simple templating language (that you're looking at right now) for generating random messages from a {template|message|sequence of words}. Add a couple {synonyms|options} and send everyone a different version.

{It can do|It{ even|} does} nested messages{ if you're feeling creative}!
